services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: bash -c "python -m main"
    networks:
      - backend  



  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    env_file: .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    networks:
      - backend  
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/001.sql
  
networks:
  backend:
    driver: bridge